import { promises as fs } from 'fs'
import path from 'path'

const APPS_DIR = path.join(process.cwd(), 'apps')
const OUT_FILE = path.join(process.cwd(), 'src', 'lib', 'apps', 'registry.ts')

type ModuleType = 'view' | 'admin' | 'widget' | 'install' | 'uninstall'

async function generateRegistry() {
  const entries: { slug: string; type: ModuleType }[] = []

  const slugs = await fs.readdir(APPS_DIR)
  for (const slug of slugs) {
    const appDir = path.join(APPS_DIR, slug)
    const stat = await fs.stat(appDir).catch(() => null)
    if (!stat?.isDirectory()) continue
    const slugValid = /^[a-z0-9-]+$/.test(slug)
    if (!slugValid) continue

    for (const type of ['view', 'admin', 'widget', 'install', 'uninstall'] as ModuleType[]) {
      const ext = type === 'install' || type === 'uninstall' ? '.ts' : '.tsx'
      const filePath = path.join(appDir, `${type}${ext}`)
      try {
        await fs.access(filePath)
        entries.push({ slug, type })
      } catch {
        // file doesn't exist — skip
      }
    }
  }

  // install/uninstall use named exports, everything else uses default
  const isNamed = (t: string) => t === 'install' || t === 'uninstall'

  const lines: string[] = [
    '// Auto-generated by scripts/generate-registry.ts',
    '// DO NOT EDIT — run `pnpm build:registry` to regenerate',
    '',
    '/* eslint-disable @typescript-eslint/no-explicit-any */',
    '',
    'type RegistryEntry = () => Promise<any>',
    'const registry = new Map<string, { loader: RegistryEntry; named: boolean }>()',
    '',
  ]

  for (const { slug, type } of entries) {
    const ext = isNamed(type) ? '.ts' : '.tsx'
    const relPath = path.relative(
      path.dirname(OUT_FILE),
      path.join(APPS_DIR, slug, `${type}${ext}`)
    )
    const importPath = relPath.replace(/\.(tsx|ts)$/, '')
    lines.push(`registry.set('${slug}/${type}', { loader: () => import('${importPath}'), named: ${isNamed(type)} })`)
  }

  lines.push('')
  lines.push('export async function loadAppModule(slug: string, type: string): Promise<any> {')
  lines.push('  const entry = registry.get(`${slug}/${type}`)')
  lines.push('  if (!entry) throw new Error(`App module not found: ${slug}/${type}`)')
  lines.push('  const mod = await entry.loader()')
  lines.push('  return entry.named ? mod[type] : mod.default')
  lines.push('}')
  lines.push('')
  lines.push('export function hasAppModule(slug: string, type: string): boolean {')
  lines.push('  return registry.has(`${slug}/${type}`)')
  lines.push('}')

  await fs.writeFile(OUT_FILE, lines.join('\n'), 'utf-8')
  console.log(`Registry generated: ${OUT_FILE} (${entries.length} entries)`)
}

generateRegistry().catch(console.error)
