import { promises as fs } from 'fs'
import path from 'path'

const APPS_DIR = path.join(process.cwd(), 'apps')
const OUT_FILE = path.join(process.cwd(), 'src', 'lib', 'apps', 'registry.ts')

type ModuleType = 'view' | 'admin' | 'widget' | 'install' | 'uninstall'

async function generateRegistry() {
  const entries: { slug: string; type: ModuleType }[] = []

  const slugs = await fs.readdir(APPS_DIR)
  for (const slug of slugs) {
    const appDir = path.join(APPS_DIR, slug)
    const stat = await fs.stat(appDir).catch(() => null)
    if (!stat?.isDirectory()) continue
    const slugValid = /^[a-z0-9-]+$/.test(slug)
    if (!slugValid) continue

    for (const type of ['view', 'admin', 'widget', 'install', 'uninstall'] as ModuleType[]) {
      const ext = type === 'install' || type === 'uninstall' ? '.ts' : '.tsx'
      const filePath = path.join(appDir, `${type}${ext}`)
      try {
        await fs.access(filePath)
        entries.push({ slug, type })
      } catch {
        // file doesn't exist — skip
      }
    }
  }

  const lines: string[] = [
    '// Auto-generated by scripts/generate-registry.ts',
    '// DO NOT EDIT — run `pnpm build:registry` to regenerate',
    '',
    '/* eslint-disable @typescript-eslint/no-explicit-any */',
    '',
    'const registry = new Map<string, () => Promise<any>>()',
    '',
  ]

  for (const { slug, type } of entries) {
    const relPath = path.relative(
      path.dirname(OUT_FILE),
      path.join(APPS_DIR, slug, type === 'install' || type === 'uninstall' ? `${type}.ts` : `${type}.tsx`)
    )
    // Remove extension for the import
    const importPath = relPath.replace(/\.(tsx|ts)$/, '')
    lines.push(`registry.set('${slug}/${type}', () => import('${importPath}'))`)
  }

  lines.push('')
  lines.push('export async function loadAppModule(slug: string, type: string): Promise<any> {')
  lines.push('  const key = `${slug}/${type}`')
  lines.push('  const loader = registry.get(key)')
  lines.push('  if (!loader) throw new Error(`App module not found: ${key}`)')
  lines.push('  const mod = await loader()')
  lines.push('  return mod.default')
  lines.push('}')
  lines.push('')
  lines.push('export function hasAppModule(slug: string, type: string): boolean {')
  lines.push('  return registry.has(`${slug}/${type}`)')
  lines.push('}')

  await fs.writeFile(OUT_FILE, lines.join('\n'), 'utf-8')
  console.log(`Registry generated: ${OUT_FILE} (${entries.length} entries)`)
}

generateRegistry().catch(console.error)
