// Auto-generated by scripts/generate-registry.ts
// DO NOT EDIT — run `pnpm build:registry` to regenerate

/* eslint-disable @typescript-eslint/no-explicit-any */

type RegistryEntry = () => Promise<any>
const registry = new Map<string, { loader: RegistryEntry; named: boolean }>()

registry.set('inspiration/view', { loader: () => import('../../../apps/inspiration/view'), named: false })
registry.set('inspiration/admin', { loader: () => import('../../../apps/inspiration/admin'), named: false })
registry.set('inspiration/widget', { loader: () => import('../../../apps/inspiration/widget'), named: false })
registry.set('inspiration/install', { loader: () => import('../../../apps/inspiration/install'), named: true })
registry.set('inspiration/uninstall', { loader: () => import('../../../apps/inspiration/uninstall'), named: true })
registry.set('split-expenses/view', { loader: () => import('../../../apps/split-expenses/view'), named: false })
registry.set('split-expenses/admin', { loader: () => import('../../../apps/split-expenses/admin'), named: false })
registry.set('split-expenses/widget', { loader: () => import('../../../apps/split-expenses/widget'), named: false })
registry.set('split-expenses/install', { loader: () => import('../../../apps/split-expenses/install'), named: true })
registry.set('split-expenses/uninstall', { loader: () => import('../../../apps/split-expenses/uninstall'), named: true })
registry.set('todo/view', { loader: () => import('../../../apps/todo/view'), named: false })
registry.set('todo/admin', { loader: () => import('../../../apps/todo/admin'), named: false })
registry.set('todo/widget', { loader: () => import('../../../apps/todo/widget'), named: false })
registry.set('todo/install', { loader: () => import('../../../apps/todo/install'), named: true })
registry.set('todo/uninstall', { loader: () => import('../../../apps/todo/uninstall'), named: true })

export async function loadAppModule(slug: string, type: string): Promise<any> {
  const entry = registry.get(`${slug}/${type}`)
  if (!entry) throw new Error(`App module not found: ${slug}/${type}`)
  const mod = await entry.loader()
  return entry.named ? mod[type] : mod.default
}

export function hasAppModule(slug: string, type: string): boolean {
  return registry.has(`${slug}/${type}`)
}