// Auto-generated by scripts/generate-registry.ts
// DO NOT EDIT — run `pnpm build:registry` to regenerate

/* eslint-disable @typescript-eslint/no-explicit-any */

const registry = new Map<string, () => Promise<any>>()

registry.set('inspiration/view', () => import('../../../apps/inspiration/view'))
registry.set('inspiration/admin', () => import('../../../apps/inspiration/admin'))
registry.set('inspiration/widget', () => import('../../../apps/inspiration/widget'))
registry.set('inspiration/install', () => import('../../../apps/inspiration/install'))
registry.set('inspiration/uninstall', () => import('../../../apps/inspiration/uninstall'))
registry.set('todo/view', () => import('../../../apps/todo/view'))
registry.set('todo/admin', () => import('../../../apps/todo/admin'))
registry.set('todo/widget', () => import('../../../apps/todo/widget'))
registry.set('todo/install', () => import('../../../apps/todo/install'))
registry.set('todo/uninstall', () => import('../../../apps/todo/uninstall'))

export async function loadAppModule(slug: string, type: string): Promise<any> {
  const key = `${slug}/${type}`
  const loader = registry.get(key)
  if (!loader) throw new Error(`App module not found: ${key}`)
  const mod = await loader()
  return mod.default
}

export function hasAppModule(slug: string, type: string): boolean {
  return registry.has(`${slug}/${type}`)
}